{
  "openapi": "3.0.1",
  "info": {
    "title": "w2work3",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/api/v1/user/signup": {
      "post": {
        "summary": "注册user",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "username": "test11234",
                "password": "123456"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 200,
                  "msg": "success"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/v1/user/login": {
      "post": {
        "summary": "登录user",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "username": "test11234",
                "password": "123456"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 200,
                  "msg": "success",
                  "data": {
                    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6InRlc3QxMTIzNCIsImV4cCI6MTc3NDA4MzU3OX0.7jivLTxEPkwB_AUgCBAfvSBPppb5jdaWoIffTFZn_OU"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/v1/user/delete": {
      "delete": {
        "summary": "删除user",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "username": "test11234",
                "password": "123456"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 200,
                  "msg": "success"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/v1/todo/create": {
      "post": {
        "summary": "创建Todo",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "title": "完成 go 作业",
                "content": "把 handler、service、repository 都联调完",
                "start_time": "2026-03-19T10:00:00Z",
                "end_time": "2026-03-20T10:00:00Z"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 100,
                  "msg": "success",
                  "data": {
                    "TodoID": 1
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "jwt": []
          }
        ]
      }
    },
    "/api/v1/todo/list": {
      "post": {
        "summary": "查询todo",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": "{\n  \"page\": 1,\n  \"pagesize\": 1,\n  \"status\":true,\n}\n"
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 200,
                  "msg": "success",
                  "data": {
                    "items": [
                      {
                        "id": 1,
                        "title": "完成 go 作业",
                        "content": "把 handler、service、repository 都联调完",
                        "view": 0,
                        "status": false,
                        "create_at": "2026-03-20T17:00:39.705507+08:00",
                        "start_time": "2026-03-19T18:00:00+08:00",
                        "end_time": "2026-03-20T18:00:00+08:00"
                      }
                    ],
                    "total": 1
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "jwt": []
          }
        ]
      }
    },
    "/api/v1/todo/update": {
      "patch": {
        "summary": "更新Todo",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "id": 1,
                "title": "完成 Go Web 作业（更新版）",
                "content": "补完 main.go、jwt middleware，并修复删除逻辑",
                "status": true,
                "start_time": "2026-03-20T10:00:00Z",
                "end_time": "2026-03-23T10:00:00Z"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 200,
                  "msg": "success"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "jwt": []
          }
        ]
      }
    },
    "/api/v1/todo/status": {
      "patch": {
        "summary": "批量更新todo状态",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "ids": [
                  3
                ],
                "status": true
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 200,
                  "msg": "success"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "jwt": []
          }
        ]
      }
    },
    "/api/v1/todo/delete": {
      "delete": {
        "summary": "删除todo",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": "{\n  \"ids\": [\n    1,\n  ]\n}"
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 200,
                  "msg": "success"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "jwt": []
          }
        ]
      }
    },
    "/api/v1/todo/delete/status": {
      "delete": {
        "summary": "按状态删除todo",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "status": true
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 200,
                  "msg": "success",
                  "data": {
                    "total": 2
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "jwt": []
          }
        ]
      }
    },
    "/api/v1/todo/delete/all": {
      "delete": {
        "summary": "删除所有todo",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 200,
                  "msg": "success",
                  "data": {
                    "total": 1
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "jwt": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {
      "jwt": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "servers": [],
  "security": []
}